from dataclasses import dataclass


class PlotType:
    """
    Base marker class representing a generic plot type.

    Attributes
    ----------
    value : str
        The string representation of the plot type used by the UI dropdowns.
    """

    value: str


class Section:
    """
    Base marker class representing a generic plot type.

    Attributes
    ----------
    value : str
        The string representation of the plot type used by the UI dropdowns.
    """

    value: str


@dataclass
class Line(PlotType):
    """
    Marker class for a 1D line plot.

    Attributes
    ----------
    value : str
        The string representation of the plot type, defaults to "Line".
    """

    value = "Line"


@dataclass
class Heatmap(PlotType):
    """
    Marker class for a standard 2D heatmap plot.

    Attributes
    ----------
    value : str
        The string representation of the plot type, defaults to "Heatmap".
    """

    value = "Heatmap"


class MultiplotHeatmap(PlotType):
    """
    Marker class for a 2D heatmap configured for a multi-plot grid.

    Attributes
    ----------
    value : str
        The string representation of the plot type, defaults to "Heatmap (grid)".
    """

    value = "Heatmap (grid)"


@dataclass
class Animation(PlotType):
    """
    Marker class for a 3D animation plot.

    Attributes
    ----------
    value : str
        The string representation of the plot type, defaults to "Animation".
    """

    value = "Animation"


@dataclass
class User(Section):
    value = (
        "user"  # not sure if this is even necessary but can I define an empty class?
    )


@dataclass
class Ref(Section):
    value = "ref"


@dataclass
class Multiplot(Section):
    value = "multiplot"


@dataclass
class PlotValidationResult:
    """
    Container for plot validation results generated by the controller.

    Attributes
    ----------
    plot_valid : bool
        True if the configuration is completely valid and ready to plot. Defaults to False.
    requires_slice : bool
        True if unplotted dimensions require slicing widgets to be created. Defaults to False.
    invalid_heatmap_data : bool
        True if the plot type lacks sufficient dimensions or required axes. Defaults to False.
    same_axes_chosen : bool
        True if duplicate axes were selected for different plot dimensions. Defaults to False.
    prompt_bounds : bool
        True if bounds prompting is required before plotting (used in multiplot). Defaults to False.
    """

    plot_valid: bool = False
    requires_slice: bool = False
    invalid_heatmap_data: bool = False
    same_axes_chosen: bool = False
    prompt_bounds: bool = False
